# Generated by Django 2.2.5 on 2019-10-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publoshed_date',
            new_name='published_date',
        ),
    ]
